[package]
name = "gui"
version = "0.1.0"
authors = ["Galilée 'Bill' Enguehard <galilee.enguehard@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
conrod_core = "0.63"
conrod_glium = "0.63"
conrod_winit = "0.63"
glium = "0.23"
