[package]
name = "daemon"
version = "0.1.0"
authors = ["Galilee 'Bill' Enguehard <galilee.enguehard@gmail.com>"]
edition = "2018"

[dependencies]

api = { path = "../api" }
wayland-client = "0.21.11"
wayland-protocols = "0.21.11"
smithay-client-toolkit = "0.4.4"
libc = "0.2.48"
log = "0.4"
