[package]
name = "api"
version = "0.1.0"
authors = ["Galilee 'Bill' Enguehard <galilee.enguehard@gmail.com>"]
edition = "2018"

[dependencies]

config = "0.9"
serde = "1.0"
serde_derive = "1.0"
log = "0.4"
bincode = "1.1"
